### PR TITLE
Move stalled projects to stalled development

### PR DESCRIPTION
**Pull request by n-ce**
This is a PR in progress which hopes to move old libraries that have not been updated in a year or more to stalled development

### CODE REVIEW

**Comment by n-ce** [comment]
I have completed the transition. This also included bringing back recently removed Normalize to s.d. I also did not remove XP.css because I couldn't make a decision if it should be removed.
This PR is meant to be squash merged.

**Comment by troxler** [comment]
Thanks for taking the time to go through the list! I mostly like the changes but have two remarks.

* The specialized sections contains some niche framework that are only useful for very specific use cases. In these cases, using a framework that solves the need is more important than to be up to date. For example, if you want your website to look like NES, then you should use the corresponding framework. I think the inactivity policy should no strictly apply for this section and no frameworks should currently be moved to the stalled section.

* normalize.css has not seen any update whatsoever in the last (almost) five years. And its author refused to comment on the project's state. I think it safe to say that this project is outdated and will likely not come back. I do not think it should be listed anymore.

What do you think?

**Comment by n-ce** [comment]
I agree with your reasoning. I'll make the necessary changes.

**Comment by troxler** [comment]
Thanks!

**Pull request merged**
