### PR TITLE
Add minstyle.io

### PR DESCRIPTION
**Pull request by Airmime**
Hello,

I just published the V2 of the framework, feel free to add it to the list if you think it is relevant 😄 

Thanks,

### CODE REVIEW

**Comment by troxler** [comment]
Thanks for the suggestion. I did not really have a closer look as already your landing page leaves a bad impression, sorry. There are severe issues with responsiveness. Some elements have way too much horizontal spacing (see the screenshot) which makes reading their content impossible. Some other elements have no spacing at all. And there is horizontal scrolling for no apparent reason. Having good support for mobile devices is most definitely a hard requirement for all the frameworks in this list.

Feel free to ping me when your framework has better support for responsiveness.

Screenshot 2022-03-27 at 12 22 46

**Comment by Airmime** [comment]
Thank you for your answer. Indeed, I still have some work to do on the new version (on the documentation in particular) which is in beta. I will ping you when it will be more stable :)

**Comment by Airmime** [comment]
Hello,

I made several corrections on the framework and the website. Should I open a new PR?

Thanks 😄

**Comment by troxler** [comment]
I had a quick look and found two things that are nogos. 1)There are no focus stylings on buttons and other interactive elements. This makes it impossible to use your framework with a keyboard. 2) You provide classes for mark, code, kbd, blockquotes, hr. There are perfectly fine *semantic* ways to annotate your content accordingly. No need for classes, and especially not with a `div` that has to be set as `display:inline` to work properly. `div`s are _block_ elements by default. If you need an inline element when no other element is suitable, use `span`.

Aside from that, it seems minstyle is not yet that popular. But both a certain maturity and popularity is required to be added to this list. So you should work on both quality and popularity of your framework. In its current state, I'm afraid, it is not a good match.

**Pull request closed without merging**
