### PR TITLE
Added Doodle CSS

### PR DESCRIPTION
**Pull request by jules-lewis**

### CODE REVIEW

**Comment by troxler** [comment]
Blocked by https://github.com/chr15m/DoodleCSS/issues/9

**Review by Nanito369 — APPROVED** [review]

**Comment by troxler** [comment]
The blocking issue is still open. So I'm closing this for now, feel free to reopen.

**Comment by troxler** [comment]
@chr15m Thanks for the update. I'm still a little reluctant to add this framework to the list.

* Buttons look very similar to inputs with text.
* Disabled buttons look very similar to inputs with a placeholder.
* It has a dependency on Google Fonts. Additionally, it only defines `cursive` as a fallback font which may look very different to `Short Stack` and may be hard to read. Ideally, you would include the custom font in your own code and remove the dependency on Google.

**Comment by chr15m** [comment]
Ok no problem, thanks.

**Pull request closed without merging**
