### PR TITLE
CSS Remedy, ress and A Modern CSS Reset (Base/Reset/Normalize)

### PR DESCRIPTION
**Pull request by RinatValiullov**
I think this tool of Jen Simmons(Mozilla) must be in Base / Reset / Normalize section too

### CODE REVIEW

**Comment by troxler** [comment]
Thanks, that looks very interesting! Currently it still looks *very* early stage but I will merge it as soon as it more stable.

**Comment by RinatValiullov** [comment]
@troxler can you look at this proposal?

Found this tiny reset and think it will suit here well:

[ress](https://github.com/filipelinhares/ress) - Modern css reset

**Comment by RinatValiullov** [comment]
@troxler 

Found this tiny reset and think it will suit here well:

[ress](https://github.com/filipelinhares/ress) - Modern css reset

**Comment by RinatValiullov** [comment]
@troxler 

Yet another reset:
[A Modern CSS Reset](https://github.com/hankchizljaw/modern-css-reset)

**Comment by troxler** [comment]
Thanks for those suggestions. But can you please create new PRs for each link? This makes it possible to assess and merge each item individually. Currently, this whole PR cannot be merged because CSS Remedy does not comply with this list's standards yet.

**Comment by RinatValiullov** [comment]
@troxler Ok.
As I don't know how to make 3 separate PR correctly. I will delete this one and remake new three separate? Is it good?

**Pull request closed without merging**
