### PR TITLE
Adds AgnosticUI

### PR DESCRIPTION
**Pull request by roblevintennis**

### CODE REVIEW

**Comment by troxler** [comment]
Thanks for the suggestion. AgnosticUI seems to be a component library, not really a CSS framework. At least that is my impression from reading their docs. While they claim that vanilla JS is supported, I don't see any example in the actual documentation. For example, https://www.agnosticui.com/docs/components/buttons.html does not explain how to use these Buttons with CSS and/or vanilla JS.

As you are the creator of AgnosticUI, can you clarify?

**Comment by roblevintennis** [comment]
Thanks for the feedback and question.

What's a CSS framework in your opinion? I ask because "framework" is generally a misnomer e.g. Bootstrap is certainly not a framework but a library. Same for  TailWind is more of a framework to my mind because there's a whole JIT compiler to prune unused classes etc. But something like Angular that has an entire runtime, command line interface, inversion of control, and general prescription of all the things, etc., is what falls under framework to my mind. Sorry for long digression though; I suppose googling "library vs framework" has the best answer to all this.

In terms of platform JavaScript and/or CSS the https://github.com/AgnosticUI/agnosticui/tree/master/agnostic-css aka CSS package has examples. In short, any component starts in there e.g. button.html and button.css, then, the css contents get copied to framework implementations. So, in a platform HTML/CSS/JavaScript based project, you'd simply import the CSS only.

So you could import https://github.com/AgnosticUI/agnosticui/blob/master/agnostic-css/css-dist/components.prefixed.min.css and go to town.

Actually, the landing page shows an example of this as well:

image


Does that answer your question?

**Comment by troxler** [comment]
It was not my intention to discuss the differences between frameworks and libraries. I don't think it matters much in this context. This list contains tools that are closer to a framework and others that are closer to a library.

Most tools listed so far provide a CSS file that can be added to an HTML document and some styles are already applied. AgnosticUI on the other hand seems to target some of the larger JavaScript frameworks/libraries. It provides components that the users can use. Hence, I called it a "*component* library". There is currently no *component* library in the list that does not also provide a documentation for vanilla JavaScript (with Web Components).

> Actually, the landing page shows an example of this as well

My point was that this seems to be the *only* mention of that. I don't see anything related to it in the documentation. For example, how are users supposed to find out about possible CSS classes they can apply to a button element? Checking the CSS code may be one—but certainly not the best—way. AgnosticUI may actually be a fit for this list. I just find your documentation very lacking if you target vanilla JavaScript.

**Comment by roblevintennis** [comment]
Gotcha. So I think you're feedback makes sense the docs are definitely not going much into that usage case much--I'm going to add a section in the usage docs to show how that works. Thanks for sharing your feedback!

**Comment by roblevintennis** [comment]
http://www.agnosticui.com/docs/setup.html#platform-html-css-javascript added

**Comment by roblevintennis** [comment]
@troxler I just wanted to mention your feedback has prompted me to start to work on splitting out the component docs into "Framework Components" and "CSS Components". I really don't want to mix the two since they're usage is so different but you can see the gist of where I'm going with this here:

image

If you don't mind I'd like to keep this PR here open until I can get this done (maybe 1-2 weeks I'm thinking) and then perhaps I can at-mention you so you can have a look.

Thanks again for your feedback!

**Comment by troxler** [comment]
Nice! Sure, just ping me when you're ready.

**Comment by roblevintennis** [comment]
I think the CSS docs are good to go:
https://www.agnosticui.com/docs/css/alerts.html 

I've added a couple of videos and actually started out with going into how to use the agnostic-css package:
https://www.youtube.com/watch?v=sCLc2ttYJ2A 
https://www.youtube.com/watch?v=MjYGN7asGZo

**Comment by troxler** [comment]
Hi @roblevintennis. Thanks for the effort! I finally had a closer look, here are some findings:

* The focus styling of blue buttons is not visible enough.
* The color contrast of the checkboxes and radio buttons is way too low, especially in dark mode.
* The color contrast of focused radio buttons is also quite low (focussed checkboxes have a different focus color).
* Warning text blocks are unreadable in dark mode.
* The color contrast of input fields' borders is very low, especially in dark mode.
* The color contrast of the Switch is too low (especially in the dark mode again). The component looks like a white pill, not like a switch. Also the color difference of checked switches is too low.
* The table header in the dark mode has an almost invisible bottom border.
* The table in dark mode with a hover effect makes its text disappear.
* The color contrast on tab borders is way too low.

You should really look in all these accessibility problems. Especially in dark mode, I do not think that your styling is very pleasant to use. But the contrast in light mode are too low as well. If you are open to improve these things, you can ping me when I should have another look. If not, please close this PR.

**Comment by roblevintennis** [comment]
Thanks for sharing your feedback with me 👍🏽

**Pull request closed without merging**
